##
##  ci.yml
##  Networker
##
##  Created by Ariel Elkin on 22/09/2020.
##  Copyright © 2020 TGR1.618 Ltd. All rights reserved.
##

name: CI

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:

jobs:
  primary:
    name: Primary
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2

      - name: SwiftLint
        run: |
          curl -OJ https://raw.githubusercontent.com/shapedbyiris/swiftlint-config/master/swiftlint.yml
          swiftlint lint --strict --config swiftlint.yml

      - name: Build
        run: swift build

      - name: Test
        run: swift test

      - name: Pod Lint
        run: pod lib lint --private --verbose
